owner: SRESchool
repo: AllJetexe-monitor-upptime
sites:
  - name: AIAviationAcademy
    url: https://aiaviationacademy.com
    ssl: true
  - name: AircraftO
    url: https://aircrafto.com
    ssl: true
  - name: CharterKings
    url: https://charterkings.com
    ssl: true
  - name: ExecutiveAirRepair
    url: https://executiveairrepair.com
    ssl: true
  - name: FlightTrainingUS
    url: https://flighttrainingus.com
    ssl: true
  - name: FlyAIAA
    url: https://flyaiaa.com
    ssl: true
  - name: JetAndRotor
    url: https://jetandrotor.com
    ssl: true
  - name: JetExe
    url: https://jetexe.com
    ssl: true
  - name: KitPlanePart
    url: https://kitplanepart.com
    ssl: true
  - name: LearnFlying
    url: https://learnflying.com
    ssl: true
  - name: LightSportWest
    url: https://lightsportwest.com
    ssl: true
  - name: PilotsDeal
    url: https://pilotsdeal.com
    ssl: true
  - name: PegasusEstates
    url: https://pegasus-estates.com
    ssl: true
  - name: PilotsIndia
    url: https://pilotsindia.com
    ssl: true
  - name: PilotTrainingUS
    url: https://pilottrainingus.com
    ssl: true
  - name: PlanesPart
    url: https://planespart.com
    ssl: true
  - name: ProEzi
    url: https://proezi.com
    ssl: true
  - name: BuyMLocal
    url: https://buymlocal.com
    ssl: true
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: null
  baseUrl: /AllJetexe-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AllJetexe Uptime Monitor
  introTitle: "**Upptime** monitoring for Jetexe-related websites"
  introMessage: Real-time uptime and SSL status for multiple websites, powered by GitHub.
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/SRESchool/AllJetexe-monitor-upptime

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"

assignees:
  - SRESchool
